USE [omoprawdata]
GO

/****** Object:  Table [dbo].[S5ALL23]    Script Date: 5/13/2019 1:45:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[S5ALL23](
	[IDNO] [nvarchar](255) NULL,
	[FAMID] [nvarchar](255) NULL,
	[SEX] [nvarchar](255) NULL,
	[S5EXDATE] [datetime] NULL,
	[S5INCOME] [nvarchar](255) NULL,
	[S5KF] [nvarchar](255) NULL,
	[S5KD] [nvarchar](255) NULL,
	[S5KT] [nvarchar](255) NULL,
	[CENTER] [nvarchar](255) NULL,
	[INT25_67] [nvarchar](255) NULL,
	[S5ETOH] [nvarchar](255) NULL,
	[S5SMOKE] [nvarchar](255) NULL,
	[EX5_42] [float] NULL,
	[S5HT] [float] NULL,
	[S5WT] [float] NULL,
	[S5HIP] [float] NULL,
	[S5WAIST] [float] NULL,
	[S5BMI] [float] NULL,
	[S5WHR] [float] NULL,
	[S5LBM] [float] NULL,
	[S5FAT] [float] NULL,
	[S5BDFAT] [float] NULL,
	[S5SBP] [float] NULL,
	[S5DBP] [float] NULL,
	[S5MBP] [float] NULL,
	[S5PP] [float] NULL,
	[S5HTNRX] [nvarchar](255) NULL,
	[S5WHOHTN] [nvarchar](255) NULL,
	[S5USHTN] [nvarchar](255) NULL,
	[S5HTNHX] [nvarchar](255) NULL,
	[S5RT_AAR] [float] NULL,
	[S5LT_AAR] [float] NULL,
	[S5WBC] [float] NULL,
	[S5RBC] [float] NULL,
	[S5HGB] [float] NULL,
	[S5HCT] [float] NULL,
	[S5MCV] [float] NULL,
	[S5PLT] [float] NULL,
	[S5NEUT] [float] NULL,
	[S5P_CREA] [float] NULL,
	[S5CRP] [float] NULL,
	[S5HDL] [float] NULL,
	[S5G0] [float] NULL,
	[S5INSU] [float] NULL,
	[S5LDL] [float] NULL,
	[S5TG] [float] NULL,
	[S5U_ALB] [float] NULL,
	[S5TC] [float] NULL,
	[S5HBA1C] [float] NULL,
	[S5UCREA] [float] NULL,
	[S5CCR] [float] NULL,
	[S5UACR] [float] NULL,
	[S5ACR] [nvarchar](255) NULL,
	[S5LACR] [float] NULL,
	[S5ACR2] [nvarchar](255) NULL,
	[S5LPTRT] [nvarchar](255) NULL,
	[S5DMHX] [nvarchar](255) NULL,
	[S5DMTX] [nvarchar](255) NULL,
	[S5ADADM] [nvarchar](255) NULL,
	[S5HOMAIR] [float] NULL,
	[S5ADADMD] [float] NULL,
	[S5UACID] [float] NULL,
	[S5EDU] [float] NULL,
	[S5AGE] [float] NULL,
	[S5GFRM2] [float] NULL,
	[S5GFR_EPI] [float] NULL,
	[S5ATP3MS0] [nvarchar](255) NULL,
	[S5PPY] [float] NULL,
	[s5smkd] [float] NULL,
	[s5meno] [nvarchar](255) NULL,
	[s5estro] [nvarchar](255) NULL,
	[S5P_ALB] [float] NULL,
	[S5bingeM] [nvarchar](255) NULL,
	[S5bingeY] [nvarchar](255) NULL,
	[S5HYLIPID] [nvarchar](255) NULL,
	[S5CKD] [float] NULL,
	[S5CKDSTAGE] [float] NULL
) ON [PRIMARY]
GO


