USE [omoprawdata]
GO

/****** Object:  Table [dbo].[S4ALL23]    Script Date: 5/13/2019 1:46:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[S4ALL23](
	[IDNO] [nvarchar](255) NULL,
	[FAMID] [nvarchar](255) NULL,
	[S4AGE] [float] NULL,
	[SEX] [nvarchar](255) NULL,
	[S4EXDATE] [datetime] NULL,
	[S4INCOME] [nvarchar](255) NULL,
	[S4KF] [nvarchar](255) NULL,
	[S4KD] [nvarchar](255) NULL,
	[S4KT] [nvarchar](255) NULL,
	[CENTER] [nvarchar](255) NULL,
	[S4EDU] [float] NULL,
	[S4BLOOD] [float] NULL,
	[INT24_67] [nvarchar](255) NULL,
	[S4ETOH] [nvarchar](255) NULL,
	[S4SMOKE] [nvarchar](255) NULL,
	[S4SMKD] [float] NULL,
	[S4PPY] [float] NULL,
	[EX4_42] [float] NULL,
	[S4HT] [float] NULL,
	[S4WT] [float] NULL,
	[S4HIP] [float] NULL,
	[S4WAIST] [float] NULL,
	[S4BMI] [float] NULL,
	[S4WHR] [float] NULL,
	[S4LBM] [float] NULL,
	[S4FAT] [float] NULL,
	[S4BDFAT] [float] NULL,
	[S4SBP] [float] NULL,
	[S4DBP] [float] NULL,
	[S4MBP] [float] NULL,
	[S4PP] [float] NULL,
	[S4HTNRX] [nvarchar](255) NULL,
	[S4RT_AAR] [float] NULL,
	[S4LT_AAR] [float] NULL,
	[S4WBC] [float] NULL,
	[S4RBC] [float] NULL,
	[S4HGB] [float] NULL,
	[S4HCT] [float] NULL,
	[S4MCV] [float] NULL,
	[S4PLT] [float] NULL,
	[S4NEUT] [float] NULL,
	[S4PAI1] [float] NULL,
	[S4U_ALB] [float] NULL,
	[S4P_CREA] [float] NULL,
	[S4UACID] [float] NULL,
	[S4INSU] [float] NULL,
	[S4G0] [float] NULL,
	[S4FIBRIN] [float] NULL,
	[S4TC] [float] NULL,
	[S4HDL] [float] NULL,
	[S4TG] [float] NULL,
	[S4LDL] [float] NULL,
	[S4ALT] [float] NULL,
	[S4AST] [float] NULL,
	[S4ALB] [float] NULL,
	[S4BUN] [float] NULL,
	[S4CO2] [float] NULL,
	[S4CAL] [float] NULL,
	[S4CHL] [float] NULL,
	[S4PHOSP] [float] NULL,
	[S4POT] [float] NULL,
	[S4SOD] [float] NULL,
	[S4TBILI] [float] NULL,
	[S4TPROT] [float] NULL,
	[S4HBA1C] [float] NULL,
	[S4APOA1] [float] NULL,
	[S4APOB] [float] NULL,
	[S4U_CREA] [float] NULL,
	[S4GFR] [float] NULL,
	[S4CCR] [float] NULL,
	[S4UACR] [float] NULL,
	[S4ACR] [nvarchar](255) NULL,
	[S4LACR] [float] NULL,
	[S4ACR2] [nvarchar](255) NULL,
	[MED4_8] [nvarchar](255) NULL,
	[S4DMTX] [nvarchar](255) NULL,
	[S4HOMAIR] [float] NULL,
	[S4MENO] [nvarchar](255) NULL,
	[S4ESTRO] [nvarchar](255) NULL,
	[S4LPTRT] [nvarchar](255) NULL,
	[S4HTNHX] [nvarchar](255) NULL,
	[S4DMHX] [nvarchar](255) NULL,
	[S4ATP3MS] [nvarchar](255) NULL,
	[S4MSCORE] [float] NULL,
	[S4USHTN] [nvarchar](255) NULL,
	[S4HTN2] [nvarchar](255) NULL,
	[S4HTNHX2] [nvarchar](255) NULL,
	[S4HTNRX2] [nvarchar](255) NULL,
	[S4ATP3MSN] [nvarchar](255) NULL,
	[S4MSCORN] [float] NULL,
	[S4ADADM] [nvarchar](255) NULL,
	[S4CRP] [float] NULL,
	[s4dmn1] [float] NULL,
	[MED4_10] [float] NULL,
	[S4ADADMD] [float] NULL,
	[S4GFRM2] [float] NULL,
	[S4GFR_EPI] [float] NULL,
	[S4ATP3MS0] [nvarchar](255) NULL
) ON [PRIMARY]
GO


